const DoctorsProfile = [
    {
        id: 1,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 2,
        image: '/Doctors-Image/Doctor2.svg',
        name: "Dr. Ibukun Awooloja",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Hydro Facials",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 3,
        image: '/Doctors-Image/Doctor3.svg',
        name: "Dr. Mark Maison",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Chemical peeling, Body care",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 4,
        image: '/Doctors-Image/Doctor4.svg',
        name: "Dr. John doe",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 5,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 6,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 7,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 8,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 9,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 10,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 11,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 12,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 13,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    },
    {
        id: 14,
        image: '/Doctors-Image/Doctor1.svg',
        name: "Dr. Faith Iwejunwa",
        post: "Dermatologist",
        title: "MBBs, FCPS (Dermatology)",
        specialization: "Acne and Scar Treatment.",
        callNow: "08034532123",
        status: "online",
        verified: true,
    }
]



export default DoctorsProfile;